<#
.SYNOPSIS
	Returns a custom object containing basic, useful information from a set of flows. "Useful information" includes process name, count, source ip, destination ip, etc. sorted by unique where applicable.

.DESCRIPTION
	This script is intended to be used with data structures generated by API calls made to a GuardiCore management server. It takes an array of net flows and creates a custom PowerShell object containing sorted data pulled from the array.

	Specifically, the data pulled includes:

	-Source Process Name(s)
	-Destination Process Name(s)
	-Count of flow objects
	-Total number of connections (some flows have more than one connection)
	-Source IP address(es)
	-Destination IP address(es)
	-Destination Port(s)
	
.PARAMETER Flows
	[System.Array] Net flows, as formatted from GuardiCore (converted from JSON). Can also be piped in.
	
.PARAMETER Title
	[System.String] Title of the resultant object. Defaults to "Flows".
	
.INPUTS
	System.Array (Parameter: Flows)

.OUTPUTS
	System.Object.PSCustomObject

#>



Param (
	#An array of flows, as formatted from GuardiCore (converted from JSON). Can also be piped in.
	[Parameter(Mandatory=$true,ValueFromPipeline=$true)][System.Array]$Flows,
	[System.String]$Title = "Flows"
	
)

Import-Module .\Centra.psm1

$Count = $Flows.count
$Total = $Flows | Get-GCFlowTotal
$Sources = $Flows.source_ip | Sort -Unique
$SourceProcesses = $Flows.source_process_name | Sort -Unique
$Destinations = $Flows.destination_ip | Sort -Unique
$DestinationProcesses = $Flows.destination_process_name | Sort -Unique
$DestinationPorts = $Flows.destination_port | Sort -Unique

$Output = [PSCustomObject]@{
	"Title" = $Title
	"Total Flows" = $Count
	"Total Connections" = $Total
	Sources = $Sources
	"Source Processes" = $SourceProcesses
	Destinations = $Destinations
	"Destination Processes" = $DestinationProcesses
	"Destination Ports" = $DestinationPorts
}

Return $Output